var _australia_address_identifier_test_8java =
[
    [ "com.ibm.research.drl.dpt.providers.identifiers.AustraliaAddressIdentifierTest", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1providers_1_1identifiers_1_1_australia_address_identifier_test.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1providers_1_1identifiers_1_1_australia_address_identifier_test" ]
];