var _case_insensitive_name_identifier_8java =
[
    [ "com.ibm.research.drl.dpt.providers.identifiers.CaseInsensitiveNameIdentifier", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1providers_1_1identifiers_1_1_case_insensitive_name_identifier.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1providers_1_1identifiers_1_1_case_insensitive_name_identifier" ]
];