var _f_h_i_r_questionnaire_group_question_8java =
[
    [ "com.ibm.research.drl.dpt.models.fhir.subtypes.FHIRQuestionnaireGroupQuestion", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1models_1_1fhir_1_1subtypes_1_1_f_h_i_r_questionnaire_group_question.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1models_1_1fhir_1_1subtypes_1_1_f_h_i_r_questionnaire_group_question" ]
];