var _f_h_i_r_observation_reference_range_8java =
[
    [ "com.ibm.research.drl.dpt.models.fhir.subtypes.FHIRObservationReferenceRange", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1models_1_1fhir_1_1subtypes_1_1_f_h_i_r_observation_reference_range.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1models_1_1fhir_1_1subtypes_1_1_f_h_i_r_observation_reference_range" ]
];