var _f_h_i_r_medication_administration_8java =
[
    [ "com.ibm.research.drl.dpt.models.fhir.resources.FHIRMedicationAdministration", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1models_1_1fhir_1_1resources_1_1_f_h_i_r_medication_administration.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1models_1_1fhir_1_1resources_1_1_f_h_i_r_medication_administration" ]
];