var _f_h_i_r_resource_masking_configuration_8java =
[
    [ "com.ibm.research.drl.dpt.providers.masking.fhir.FHIRResourceMaskingConfiguration", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1providers_1_1masking_1_1fhir_1_1_f_h_i_r_resource_masking_configuration.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1providers_1_1masking_1_1fhir_1_1_f_h_i_r_resource_masking_configuration" ]
];