var _f_h_i_r_device_component_production_specification_8java =
[
    [ "com.ibm.research.drl.dpt.models.fhir.subtypes.FHIRDeviceComponentProductionSpecification", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1models_1_1fhir_1_1subtypes_1_1_f_h_i_r_device_component_production_specification.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1models_1_1fhir_1_1subtypes_1_1_f_h_i_r_device_component_production_specification" ]
];