var _generalization_hierarchy_8java =
[
    [ "com.ibm.research.drl.dpt.anonymization.hierarchies.GeneralizationHierarchy", "interfacecom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1anonymization_1_1hierarchies_1_1_generalization_hierarchy.html", "interfacecom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1anonymization_1_1hierarchies_1_1_generalization_hierarchy" ]
];