var _global_certainty_penalty_test_8java =
[
    [ "com.ibm.research.drl.dpt.anonymization.informationloss.GlobalCertaintyPenaltyTest", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1anonymization_1_1informationloss_1_1_global_certainty_penalty_test.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1anonymization_1_1informationloss_1_1_global_certainty_penalty_test" ]
];