var _italian_stop_words_identifier_8java =
[
    [ "com.ibm.research.drl.dpt.providers.identifiers.ItalianStopWordsIdentifier", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1providers_1_1identifiers_1_1_italian_stop_words_identifier.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1providers_1_1identifiers_1_1_italian_stop_words_identifier" ]
];