var _latitude_longitude_hierarchy_8java =
[
    [ "com.ibm.research.drl.dpt.anonymization.hierarchies.datatypes.LatitudeLongitudeHierarchy", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1anonymization_1_1hierarchies_1_1datatypes_1_1_latitude_longitude_hierarchy.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1anonymization_1_1hierarchies_1_1datatypes_1_1_latitude_longitude_hierarchy" ]
];