var _medical_abbreviation_identifier_8java =
[
    [ "com.ibm.research.drl.dpt.providers.identifiers.MedicalAbbreviationIdentifier", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1providers_1_1identifiers_1_1_medical_abbreviation_identifier.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1providers_1_1identifiers_1_1_medical_abbreviation_identifier" ]
];