var _non_uniform_entropy_test_8java =
[
    [ "com.ibm.research.drl.dpt.anonymization.informationloss.NonUniformEntropyTest", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1anonymization_1_1informationloss_1_1_non_uniform_entropy_test.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1anonymization_1_1informationloss_1_1_non_uniform_entropy_test" ]
];