var _p_d_f_free_text_format_processor_test_8java =
[
    [ "com.ibm.research.drl.dpt.processors.PDFFreeTextFormatProcessorTest", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1processors_1_1_p_d_f_free_text_format_processor_test.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1processors_1_1_p_d_f_free_text_format_processor_test" ]
];