var _truncated_geometric_test_8java =
[
    [ "com.ibm.research.drl.dpt.anonymization.differentialprivacy.TruncatedGeometricTest", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1anonymization_1_1differentialprivacy_1_1_truncated_geometric_test.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1anonymization_1_1differentialprivacy_1_1_truncated_geometric_test" ]
];