var docker_2src_2main_2java_2com_2ibm_2research_2drl_2dpt_2toolkit_2transaction__uniqueness_2_transaction_uniqueness_options_8java =
[
    [ "com.ibm.research.drl.dpt.toolkit.transaction_uniqueness.TransactionUniquenessOptions", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1toolkit_1_1transaction__uniqueness_1_1_transaction_uniqueness_options.html", "classcom_1_1ibm_1_1research_1_1drl_1_1dpt_1_1toolkit_1_1transaction__uniqueness_1_1_transaction_uniqueness_options" ]
];